# Generated by Django 6.0.1 on 2026-01-15 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/600x600.png?text=No+Image', help_text='Paste image URL here', max_length=1000, null=True),
        ),

    ]
